# -*- coding: utf-8 -*-
"""Senitment_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Rhw9WQS7oDhhvHwzfurpxAsLxskCDEq
"""

import tweepy 
from textblob import TextBlob 
from wordcloud import WordCloud
import pandas as pd
import numpy as np 
import re
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

consumer_key = 'coyFAe2L2e3FiLkL0mjZvfCmg'
consumer_secret = 'u5pfAib1tZKN6W000gWu0xIk2MuH42sMZNpTOxcCAX1JotgFdk'
acces_token = '1197336121107050496-Fd2yrKdy9fbweM7DEM8U4Nv28wbtHe'
acces_t_secret = '970VFEOPXoyXdbYra0C0iU0rQYTCEXJONU1eclGuB4PkF'

authenticate = tweepy.OAuthHandler(consumer_key, consumer_secret)

authenticate.set_access_token(acces_token, acces_t_secret)

api = tweepy.API(authenticate, wait_on_rate_limit= True)

hashtag = api.user_timeline(screen_name='BillGates', lang='en', tweet_mode='extended', count=100)

print('show 5 tweets')
i=1
for tweet in hashtag[:5]:
  print(str(i) + ') ' + tweet.full_text + '\n')
  i += 1

df = pd.DataFrame([tweet.full_text for tweet in hashtag], columns=['Tweets'])
df.head()

def clean_text(text):
  text = re.sub(r'@[A-Za-z09]+', '', text)
  text = re.sub(r'#', '', text)
  text = re.sub(r'RT[\s]+', '', text)
  text = re.sub(r'https?:\/\/?', '', text)

  return text

df['Tweets'] = df['Tweets'].apply(clean_text)
df.head()

def get_subjectivity(text):
  return TextBlob(text).sentiment.subjectivity

def get_polarity(text):
  return TextBlob(text).sentiment.polarity

df['Subjectivity'] = df['Tweets'].apply(get_subjectivity)
df['Polarity'] = df['Tweets'].apply(get_polarity)

df.head()

all_words = ' '.join( [twts for twts in df['Tweets']])
word_Cloud = WordCloud(width=500, height=300, random_state=21, max_font_size=119).generate(all_words)

plt.imshow(word_Cloud, interpolation='bilinear')
plt.axis('off')
plt.show()

def analysis(score):
  if score < 0:
    return 'Negative'
  # elif score == 0:
  #   return 'Neutral'
  # else:
  #   return 'Positive'
  elif score > 0:
    return 'Positive'

df['Analysis'] = df['Polarity'].apply(analysis)

df

j=1
sortedDF = df.sort_values(by=['Polarity'])
for i in range(0, sortedDF.shape[0]):
  if(sortedDF['Analysis'][i] == 'Positive'):
    print(str(j) + ') ' + sortedDF['Tweets'][i])
    print()
    j += 1

j=1
sortedDF = df.sort_values(by=['Polarity'], ascending=False)
for i in range(0, sortedDF.shape[0]):
  if(sortedDF['Analysis'][i] == 'Negative'):
    print(str(j) + ') ' + sortedDF['Tweets'][i])
    print()
    j += 1

plt.figure(figsize=(8,6))
for i in range(0, df.shape[0]):
  plt.scatter(df['Polarity'][i], df['Subjectivity'][i], color='blue')

plt.title('Analisis de sentimientos')
plt.xlabel('polarity')
plt.ylabel('subjectivity')
plt.show()

ptweet = df[df.Analysis == 'Positive']
pteet = ptweet['Tweets']

round(ptweet.shape[0] / df.shape[0] * 100, 1)

ntweet = df[df.Analysis == 'Negative']
nteet = ntweet['Tweets']

round(ntweet.shape[0] / df.shape[0] * 100, 1)

df['Analysis'].value_counts()

plt.title('Sentiment Analysis')
plt.xlabel('Sentiment')
plt.ylabel('Counts')
df['Analysis'].value_counts().plot(kind='bar')
plt.show()

